name: Server ci

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/server-ci.yml"

jobs:
  styles:
    name: "Styles"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: npm ci

      - name: Check formating
        run: npm run format:check

      - name: Check linting
        run: npm run lint --max-warning=0
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        uses: npm ci

      - name: Run tests
        uses: npm run test
